# EXAMPLE PASSWORD FILE. Copy to passwords.py and set appropriately

REDDIT_BOT_NAME = ''
REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''
REDDIT_BOT_USER_NAME = ''
REDDIT_USER_PASSWORD = ''

WIKI_BOT_NAME = ''
WIKI_BOT_LOGIN = ''
WIKI_BOT_PASSWORD = ''

MASTERVAULT_PASSWORD = ''
KFDECKSERV_ADMIN_KEY = ''

PROXY_ORBIT_KEY = ''
PROXY_ROTATOR_KEY = ''
PROXY_SPIDER_KEY = ''

TWILIO_ACCOUNT_SID = ''
TWILIO_AUTH_TOKEN = ''

DISCORD_WEBOOK = ''